version: "3.8"
services:
 database:
  build:
   context: ./postgres
  image: secure_password_manager_local_database_image
  container_name: secure_password_manager_local_database_container
  ports:
   - "5432:5432"
  env_file: ./postgres/.env

